services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - PG_USER=postgres
      - POSTGRES_PASSWORD=123456
      - PG_DATABASE=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres

  api:
    depends_on:
      - postgresdb
    build:
      context: .
      target: development
    restart: unless-stopped
    env_file: .env
    ports:
      - 3500:3500
    environment:
      - PG_HOST=postgresdb
      - PG_USER=postgres
      - PG_PASSWORD=123456
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - PORT=3500
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

    command: npm run dev

  test:
    depends_on:
      - postgresdb
    build:
      context: .
      target: development
    env_file: .env
    environment:
      - PG_HOST=postgresdb
      - PG_USER=postgres
      - PG_PASSWORD=123456
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - PORT=3500
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm test

volumes:
  db:
